p = str(input('Digite algo: '))
print(f'O tipo primitivo desse valor é {type(p)}')
print(f'Sò tem espaços? {p.isspace()}')
print(f'È um número? {p.isnumeric()}')
print(f'É alfabetico? {p.isalpha()}')
print(f'É alfanumerico? {p.isalnum()}')
print(f'Esta em maiusculas? {p.isupper()}')
print(f'Esta em minuscula? {p.islower()}')
print(f'Esta capitalizada? {p.istitle()}')
